/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ec.edu.espol.workshop;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
//para probar git